version: '3.9'
services:
  gowebdav-dev:
    build:
      dockerfile: Dockerfile_dev
    container_name: gowebdav-dev

    # restart: unless-stopped
    volumes:
        - './:/workspace/GoWebDAV'
    ports:
      - '80:80'
    stdin_open: true
    tty: true