version: "3.9"
services:
  go_webdav:
    image: 117503445/go_webdav
    container_name: go_webdav
    restart: unless-stopped
    volumes:
      - "/root/dir1:/root/dir1"
      - "/root/dir2:/root/dir2"
    environment:
      - "dav=/dav1,/root/dir1,user1,pass1,true;/dav2,/root/dir2,null,null,false"
    ports:
      - "80:80"
